/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
/**
 *
 * @author xcodewarrior
 */



public class WebFrame extends javax.swing.JFrame {

    /**
     * Creates new form WebFrame
     */
    
    public static String searched = "";
    
    public WebFrame(String searchSite) {
        //initComponents();
        initAndShowGUI(searchSite);
        addWindowListener(new WindowAdapter()
        {
        public void windowClosing(WindowEvent e)
        {
            setVisible(true);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
 



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /* Create a JFrame with a JButton and a JFXPanel containing the WebView. */
    private static void initAndShowGUI(String webSiteAddress) {
        // This method is invoked on Swing thread
        JFrame frame = new JFrame("Yazılım Mühendisliği");
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        frame.getContentPane().setLayout(null); // do the layout manually
        
        //frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         frame.addWindowListener(new WindowAdapter() {
           @Override
            public void windowClosing(WindowEvent event) {
                frame.setVisible(false);
            }
        });
        
        //final JButton jButton = new JButton("Button");
        final JFXPanel fxPanel = new JFXPanel();

        //frame.add(jButton);
        frame.add(fxPanel);
        frame.setVisible(true);

        //jButton.setSize(new Dimension(800, 600));
        fxPanel.setSize(new Dimension(640, 480));
        fxPanel.setLocation(new Point(0, 27));

        frame.getContentPane().setPreferredSize(new Dimension(640, 480));
        frame.pack();
        frame.setResizable(false);

        Platform.runLater(new Runnable() { // this will run initFX as JavaFX-Thread
            @Override
            public void run() {
                System.out.println("WEb site address -> " + webSiteAddress);
                initFX(fxPanel,webSiteAddress);
            }
        });
    }
    /* Creates a WebView and fires up google.com */
    private static void initFX(final JFXPanel fxPanel , String webSite) {
        Group group = new Group();
        Scene scene = new Scene(group);
        fxPanel.setScene(scene);

        WebView webView = new WebView();

        group.getChildren().add(webView);
        webView.setMinSize(800, 800);
        webView.setMaxSize(800, 800);

            // Obtain the webEngine to navigate
        WebEngine webEngine = webView.getEngine();
        if(webSite == "")
            webEngine.load("http://www.google.com/");
        else{
            System.out.println("website -> " + webSite);
            webEngine.load(webSite);
        }
            
    }

}
